# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G4Gw-oKaGNV4GRk92KkAd3Yjgrc4kN4h
"""

# problema 1
def p01():
    """
    Calcula o consumo mensal de água em m³ a partir da leitura do hidrômetro.
    """
    # CORREÇÃO: Fechamento de parênteses no input
    anterior = int(input())
    # CORREÇÃO: Leitura do hidrômetro é um número inteiro (int), não float
    atual = int(input())

    # CORREÇÃO: Cálculo correto do consumo (atual - anterior)
    consumo = atual - anterior

    # CORREÇÃO: Nome da variável corrigido de 'consumos' para 'consumo'
    print(consumo)


# problema 2
def p02():
    """
    Calcula o valor total do frete com base na tarifa fixa e peso da carga.
    """
    tarifa = float(input())
    peso = float(input())
    # CORREÇÃO: Fechamento de parênteses no input
    valor = float(input())

    # CORREÇÃO: Fórmula do frete corrigida (tarifa + peso * valor por kg)
    frete = tarifa + (peso * valor)

    # CORREÇÃO: Nome da variável corrigido de 'total' para 'frete'
    print(f"{frete:.2f}")


# problema 3
def p03():
    """
    Classifica a qualidade do ar com base no Índice de Qualidade do Ar (IQA).
    """
    iqa = int(input())

    # CORREÇÃO: Adicionado dois-pontos ':' ao final do 'if'
    if iqa <= 50:
        print("Boa")
    # CORREÇÃO: Uso de 'elif' para encadeamento correto das faixas
    elif iqa <= 100:
        print("Moderada")
    # CORREÇÃO: Faixa de 101 a 150 ajustada para 'Ruim'
    elif iqa <= 150:
        print("Ruim")
    else:
        print("Muito ruim")


# problema 4
def p04():
    """
    Registra a entrada de veículos e exibe o total de motos e automóveis.
    """
    n = int(input())

    moto = 0
    auto = 0

    # CORREÇÃO: Adicionado dois-pontos ':' ao final da linha do 'for'
    for i in range(n):
        t = input()

        # CORREÇÃO: Operador de comparação '==' em vez de atribuição '='
        # CORREÇÃO: Tratamento para aceitar 'm' ou 'M'
        if t.upper() == "M":
            moto += 1
        else:
            # CORREÇÃO: Operador de incremento corrigido de '=+' para '+='
            auto += 1

    # CORREÇÃO: 'total' substituído pela variável 'n' (que representa o total)
    print(n)
    print(moto)
    print(auto)


# problema 5
def p05():
    """
    Identifica a maior, a menor e a média de temperaturas registradas.
    """
    n = int(input())

    # CORREÇÃO: Fechamento de parênteses no comando list()
    temps = list(map(float, input().split()))

    # CORREÇÃO: Removida a linha desnecessária 'temps[i]' dentro do for

    # Inicialização das variáveis com o primeiro elemento da lista
    maior = temps[0]
    menor = temps[0]
    soma = 0

    for t in temps:
        # CORREÇÃO: Lógica do maior trocada para operador '>'
        if t > maior:
            maior = t
        if t < menor:
            menor = t
        # CORREÇÃO: Operador de acúmulo corrigido de '=+' para '+='
        soma += t

    print(f"{maior:.1f}")
    print(f"{menor:.1f}")
    print(f"{soma/n:.2f}")


# problema 6
def p06():
    """
    Conta a quantidade total de posições contendo vegetação ('V') no mapa.
    """
    # CORREÇÃO: Fechamento de parênteses no comando map()
    n, m = map(int, input().split())

    cont = 0
    mapa = []

    for i in range(n):
        linha = input()
        mapa.append(linha)

    # CORREÇÃO: Ajuste do laço para percorrer linhas (n) e depois colunas (m)
    for i in range(n):
        for j in range(m):
            # CORREÇÃO: Comparação de caractere maiúsculo 'V'
            if mapa[i][j] == "V":
                # CORREÇÃO: Operador de incremento corrigido de '=+' para '+='
                cont += 1

    # CORREÇÃO: Nome da variável corrigido de 'contagem' para 'cont'
    print(cont)


# problema 7

def disponivel(total, emp):
    """
    Verifica se um livro possui exemplares disponíveis para empréstimo.
    """
    # CORREÇÃO: A regra de disponibilidade é ter mais exemplares que emprestados (emp < total)
    return emp < total


def p07():
    """
    Função principal do Sistema de Biblioteca que lista os livros disponíveis.
    """
    n = int(input())

    achou = False

    for i in range(n):
        titulo = input()
        total = int(input())
        emp = int(input())

        # CORREÇÃO: Ordem dos argumentos passada corretamente (total, emp)
        if disponivel(total, emp):
            # CORREÇÃO: O programa deve imprimir o 'titulo' do livro, não 'total'
            print(titulo)
            achou = True

    # CORREÇÃO: Invertida a lógica do 'if' para imprimir a mensagem apenas se NENHUM livro foi achado
    if not achou:
        print("Nenhum livro disponível.")


# problema 8

def ler_matriz(l, p):
    """
    Lê a matriz de passageiros por linha de ônibus e parada.
    """
    mat = []
    # CORREÇÃO: Adicionado dois-pontos ':' ao final da linha do 'for'
    for i in range(l):
        mat.append(list(map(int, input().split())))
    return mat


def total_linha(v):
    """
    Soma a quantidade total de passageiros em uma linha de ônibus.
    """
    s = 0
    for x in v:
        # CORREÇÃO: Operador de acúmulo corrigido de '=+' para '+='
        s += x
    return s


def melhor(mat):
    """
    Determina a linha com maior quantidade de passageiros.
    """
    idx = 0
    maior = total_linha(mat[0])

    for i in range(1, len(mat)):
        t = total_linha(mat[i])

        # CORREÇÃO: Condição para encontrar o MAIOR valor alterada para operador '>'
        if t > maior:
            maior = t
            idx = i

    # Retorna o índice da linha (1-based) e o total acumulado
    return idx + 1, maior


def p08():
    """
    Função principal para o cálculo da rota de ônibus mais movimentada.
    """
    l, p = map(int, input().split())

    # CORREÇÃO: Ordem correta dos parâmetros de dimensão da matriz (l, p)
    mat = ler_matriz(l, p)

    linha, total = melhor(mat)

    # CORREÇÃO: Nome da variável corrigido de 'linhas' para 'linha'
    print(linha)
    print(total)